"use client";

import { CloudRain, Droplets, LocateFixed, MapPin, RefreshCw, ThermometerSun, Wind, type LucideIcon } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { plants } from "../../data/plants";

type City = { name: string; latitude: number; longitude: number };
type Weather = { temperature: number; apparentTemperature: number; rain: number; wind: number; code: number };
type AdviceItem = { icon: LucideIcon; title: string; text: string; tone: "green" | "amber" | "blue" | "rose" };
type Props = { plantSlugs?: string[] };
const cities: City[] = [{ name: "Praha", latitude: 50.0755, longitude: 14.4378 }, { name: "Brno", latitude: 49.1951, longitude: 16.6068 }, { name: "Ostrava", latitude: 49.8209, longitude: 18.2625 }, { name: "Plzeň", latitude: 49.7384, longitude: 13.3736 }];
const outdoor: Record<string, { minTemp: number; rainSensitive?: boolean }> = { "washingtonie-statna": { minTemp: 8 }, "konopna-palma": { minTemp: -5 }, citronik: { minTemp: 10 }, granatovnik: { minTemp: 5 }, olivovnik: { minTemp: 5, rainSensitive: true }, "kaktus-echinopsis": { minTemp: 10, rainSensitive: true } };
const weatherText = (code: number) => code <= 1 ? "Jasno" : code <= 3 ? "Polojasno" : code <= 48 ? "Mlha" : code <= 67 ? "Déšť" : code <= 77 ? "Sněžení" : "Přeháňky nebo bouřky";
function Advice({ icon: Icon, title, text, tone }: AdviceItem) { const colors = { green: "bg-emerald-50 text-emerald-800", amber: "bg-amber-50 text-amber-900", blue: "bg-sky-50 text-sky-900", rose: "bg-rose-50 text-rose-900" }; return <article className={`rounded-2xl p-4 ${colors[tone]}`}><div className="flex gap-3"><Icon className="mt-0.5 shrink-0" size={19} /><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-5 opacity-90">{text}</p></div></div></article>; }
export default function WeatherAdvisor({ plantSlugs = [] }: Props) {
  const [city, setCity] = useState<City>(cities[0]); const [weather, setWeather] = useState<Weather | null>(null); const [status, setStatus] = useState("Zjišťuji počasí…");
  const load = useCallback(async (place: City) => { try { const response = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&current=temperature_2m,apparent_temperature,precipitation,rain,weather_code,wind_speed_10m&timezone=auto`); if (!response.ok) throw new Error(); const { current } = await response.json(); setWeather({ temperature: current.temperature_2m, apparentTemperature: current.apparent_temperature, rain: current.rain ?? current.precipitation ?? 0, wind: current.wind_speed_10m, code: current.weather_code }); setStatus(""); } catch { setWeather(null); setStatus("Počasí se teď nepodařilo načíst. Zkuste to prosím znovu."); } }, []);
  useEffect(() => { if (!navigator.geolocation) return; navigator.geolocation.getCurrentPosition(({ coords }) => setCity({ name: "Moje poloha", latitude: coords.latitude, longitude: coords.longitude }), () => undefined, { maximumAge: 300_000, timeout: 10_000 }); }, []);
  useEffect(() => { const request = window.setTimeout(() => { void load(city); }, 0); return () => window.clearTimeout(request); }, [city, load]);
  const advice = useMemo<AdviceItem[]>(() => { if (!weather) return []; const rainy = weather.rain >= 0.2 || weather.code >= 51; const selected = [...new Set(plantSlugs)].map((slug) => ({ slug, plant: plants.find((plant) => plant.slug === slug), rule: outdoor[slug] })).filter((item) => item.plant && item.rule); if (selected.length) return selected.map(({ plant, rule }) => { const name = plant!.commonName; if (weather.temperature < rule!.minTemp) return { icon: ThermometerSun, title: `${name}: přeneste dovnitř`, text: `Teplota ${Math.round(weather.temperature)} °C je pro tuto rostlinu venku příliš nízká.`, tone: "rose" }; if (weather.wind >= 35) return { icon: Wind, title: `${name}: ukryjte před větrem`, text: "Silný vítr vysušuje listy a může převrátit nádobu.", tone: "rose" }; if (rainy && rule!.rainSensitive) return { icon: CloudRain, title: `${name}: nechte pod střechou`, text: "Déšť by mohl přemokřit substrát. Dnes ji nezalévejte.", tone: "blue" }; if (rainy) return { icon: CloudRain, title: `${name}: dnes nezalévejte`, text: "Déšť doplní vláhu. Zkontrolujte jen, že voda může z květináče odtékat.", tone: "blue" }; if (weather.temperature >= 24) return { icon: Droplets, title: `${name}: zkontrolujte zálivku`, text: "Je teplo a sucho. Zalijte jen tehdy, když je vrchní vrstva substrátu suchá.", tone: "amber" }; return { icon: ThermometerSun, title: `${name}: může zůstat venku`, text: "Podmínky jsou vhodné. Se zálivkou počkejte, až substrát částečně proschne.", tone: "green" }; }); const cold = weather.temperature < 4 || weather.wind >= 35; return [cold ? { icon: ThermometerSun, title: "Teplomilné rostliny přeneste dovnitř", text: "Citroníky, olivovníky a další citlivé rostliny venku nenechávejte.", tone: "rose" } : { icon: ThermometerSun, title: "Přidejte venkovní rostliny", text: "Po jejich přidání zobrazíme doporučení přesně pro váš balkon nebo zahradu.", tone: "green" }, rainy ? { icon: CloudRain, title: "Dnes nezalévejte rostliny venku", text: "Déšť snižuje potřebu zálivky. Zkontrolujte pouze odtok vody.", tone: "blue" } : { icon: Droplets, title: "Zálivku ověřte podle substrátu", text: "Zalévejte venkovní rostliny pouze tehdy, když je vrchní vrstva substrátu suchá.", tone: "amber" }]; }, [plantSlugs, weather]);
  const locate = () => { if (!navigator.geolocation) { setStatus("Tento prohlížeč nepodporuje určení polohy."); return; } setStatus("Zjišťuji polohu…"); navigator.geolocation.getCurrentPosition(({ coords }) => setCity({ name: "Moje poloha", latitude: coords.latitude, longitude: coords.longitude }), () => setStatus("Poloha nebyla povolena. Vyberte prosím město.")); };
  return <section className="rounded-3xl bg-emerald-950 p-5 text-white shadow-sm" aria-labelledby="weather-heading"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-emerald-200">Péče podle počasí</p><h2 id="weather-heading" className="mt-1 text-2xl">Dnes v {city.name}</h2></div><button onClick={() => void load(city)} aria-label="Obnovit počasí" className="rounded-xl bg-white/10 p-2"><RefreshCw size={18} /></button></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={locate} className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-2 text-sm font-semibold text-emerald-950"><LocateFixed size={16} />Použít moji polohu</button><label className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-sm"><MapPin size={16} /><span className="sr-only">Vybrat město</span><select value={cities.some((item) => item.name === city.name) ? city.name : ""} onChange={(event) => setCity(cities.find((item) => item.name === event.target.value) ?? cities[0])} className="bg-transparent font-medium outline-none"><option value="" disabled className="text-slate-900">Moje poloha</option>{cities.map((item) => <option key={item.name} className="text-slate-900">{item.name}</option>)}</select></label></div>{weather ? <div className="mt-5 rounded-2xl bg-white/10 p-4"><div className="flex items-end justify-between"><div><p className="text-5xl font-semibold">{Math.round(weather.temperature)}°</p><p className="mt-1 text-emerald-100">{weatherText(weather.code)}, pocitově {Math.round(weather.apparentTemperature)} °C</p></div><p className="text-right text-sm text-emerald-100">Déšť {weather.rain} mm<br />Vítr {Math.round(weather.wind)} km/h</p></div></div> : <p className="mt-5 text-sm text-emerald-100">{status}</p>}{weather && <div className="mt-4 grid gap-3">{advice.map((item) => <Advice key={item.title} {...item} />)}</div>}</section>;
}
