import { ArrowLeft, Droplets, Leaf, Sprout, Sun, ThermometerSun, Waves } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import Container from "../../../components/ui/Container";
import { getPlantBySlug, plants } from "../../../data/plants";
import { getFriendlyTips } from "../../../lib/plant-friendly";

type PlantDetailPageProps = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return plants.map((plant) => ({ slug: plant.slug })); }
export default async function PlantDetailPage({ params }: PlantDetailPageProps) {
  const { slug } = await params; const plant = getPlantBySlug(slug); if (!plant) notFound();
  const essentials = [{ label: "Zálivka", value: plant.watering, icon: Droplets, color: "text-sky-600" }, { label: "Světlo", value: plant.sunlight, icon: Sun, color: "text-amber-500" }, { label: "Teplota", value: plant.temperature, icon: ThermometerSun, color: "text-rose-500" }, { label: "Vlhkost", value: plant.humidity, icon: Waves, color: "text-cyan-600" }, { label: "Hnojení", value: plant.feeding, icon: Sprout, color: "text-lime-700" }, { label: "Substrát", value: plant.soil, icon: Leaf, color: "text-emerald-700" }];
  const friendlyTips = getFriendlyTips(plant.slug, plant.thrivesWith);
  return <main className="min-h-screen bg-[#F7FAF7] pb-24 dark:bg-slate-950"><Container><div className="py-5"><Link href={`/atlas?category=${encodeURIComponent(plant.category)}`} className="inline-flex items-center gap-2 text-sm font-medium text-emerald-800 dark:text-emerald-300"><ArrowLeft size={18} />Zpět do atlasu</Link></div></Container><header className="relative h-80 overflow-hidden bg-emerald-950"><Image src={plant.image} alt={plant.commonName} fill preload sizes="(max-width: 768px) 100vw, 448px" className="object-cover opacity-85" /><div className="absolute inset-0 bg-gradient-to-t from-emerald-950 via-emerald-950/25 to-transparent" /><Container><div className="relative flex h-80 flex-col justify-end pb-8 text-white"><p className="mb-2 text-sm font-semibold uppercase tracking-[0.18em] text-emerald-100">{plant.category}</p><h1 className="text-4xl leading-tight sm:text-5xl">{plant.commonName}</h1><p className="mt-2 text-lg italic text-emerald-50">{plant.latinName}</p></div></Container></header><Container><div className="py-8"><p className="text-lg leading-8 text-slate-700 dark:text-slate-200">{plant.summary}</p><section className="mt-8"><h2 className="text-2xl font-semibold text-slate-900 dark:text-white">Co potřebuje</h2><div className="mt-4 grid gap-3">{essentials.map(({ label, value, icon: Icon, color }) => <article key={label} className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex gap-4"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-50 dark:bg-slate-800 ${color}`}><Icon size={20} /></span><div><h3 className="font-semibold text-slate-900 dark:text-white">{label}</h3><p className="mt-1 leading-6 text-slate-600 dark:text-slate-300">{value}</p></div></div></article>)}</div></section><section className="mt-8 rounded-3xl bg-emerald-900 p-6 text-white"><h2 className="text-2xl font-semibold">Co jí prospívá</h2><ul className="mt-4 space-y-3 text-emerald-50">{friendlyTips.map((tip) => <li key={tip} className="flex gap-3"><span className="mt-1 text-emerald-300">✦</span><span>{tip}</span></li>)}</ul></section><aside className="mt-5 rounded-3xl border border-amber-200 bg-amber-50 p-6"><h2 className="text-xl font-semibold text-amber-950">Na co dát pozor</h2><p className="mt-2 leading-6 text-amber-900">{plant.watchOutFor}</p></aside></div></Container></main>;
}
