"use client";

import { Bell, Moon, Send, Sun } from "lucide-react";
import { useEffect, useRef, useState } from "react";

const messages = ["Je čas zkontrolovat vláhu. 🌿", "Vaše rostliny vás zdraví.", "Podívejte se dnes na listy.", "Malá péče dnes, krásné listy zítra."];

export default function Preferences() {
  const [dark, setDark] = useState(false); const [notifications, setNotifications] = useState(false); const [message, setMessage] = useState(""); const timer = useRef<number | null>(null);
  const stop = () => { if (timer.current) window.clearInterval(timer.current); timer.current = null; };
  const send = () => { if ("Notification" in window && Notification.permission === "granted") new Notification("Flora", { body: messages[Math.floor(Math.random() * messages.length)], icon: "/images/plants/monstera.png" }); };
  useEffect(() => { const start = window.setTimeout(() => { const enabled = localStorage.getItem("flora-dark") === "true"; setDark(enabled); document.documentElement.classList.toggle("dark", enabled); }, 0); return () => window.clearTimeout(start); }, []);
  const changeTheme = (value: boolean) => { setDark(value); localStorage.setItem("flora-dark", String(value)); document.documentElement.classList.toggle("dark", value); };
  const changeNotifications = async (value: boolean) => { if (!value) { stop(); setNotifications(false); setMessage("Notifikace jsou vypnuté."); return; } if (!("Notification" in window)) { setMessage("Tento prohlížeč notifikace nepodporuje."); return; } if (await Notification.requestPermission() !== "granted") { setMessage("Oprávnění k notifikacím nebylo uděleno."); return; } stop(); timer.current = window.setInterval(send, 60_000); setNotifications(true); setMessage("Zapnuto. První upozornění přijde za jednu minutu; vypnutí je ihned zastaví."); };
  return <div className="mt-7 space-y-4"><section className="rounded-3xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex items-center justify-between gap-5"><div className="flex gap-3"><span className="text-emerald-700">{dark ? <Moon /> : <Sun />}</span><div><h2 className="font-semibold text-slate-900 dark:text-white">Tmavý režim</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-300">Šetrnější vzhled pro večer.</p></div></div><button onClick={() => changeTheme(!dark)} aria-label="Přepnout tmavý režim" className={`h-8 w-14 rounded-full p-1 ${dark ? "bg-emerald-600" : "bg-slate-200"}`}><span className={`block h-6 w-6 rounded-full bg-white transition ${dark ? "translate-x-6" : ""}`} /></button></div></section><section className="rounded-3xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex items-center justify-between gap-5"><div className="flex gap-3"><Bell className="text-emerald-700" /><div><h2 className="font-semibold text-slate-900 dark:text-white">Testovací notifikace</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-300">Jednou za minutu při otevřené aplikaci.</p></div></div><button onClick={() => void changeNotifications(!notifications)} aria-label="Přepnout testovací notifikace" className={`h-8 w-14 rounded-full p-1 ${notifications ? "bg-emerald-600" : "bg-slate-200"}`}><span className={`block h-6 w-6 rounded-full bg-white transition ${notifications ? "translate-x-6" : ""}`} /></button></div><div className="mt-4 flex flex-wrap gap-3"><button onClick={send} disabled={!notifications} className="inline-flex items-center gap-2 rounded-full bg-emerald-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Send size={16} />Poslat test nyní</button>{message && <p className="self-center text-sm text-slate-600 dark:text-slate-300">{message}</p>}</div></section></div>;
}
