"use client";

import { Check, Leaf, Plus, RotateCcw, Sprout } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import WeatherAdvisor from "../weather/WeatherAdvisor";
import { getCareProfile, plants } from "../../lib/plant-care";

type OwnedPlant = { id: string; plantSlug: string; nickname: string; fertilizedAt?: string; repottedAt?: string };
const storageKey = "flora-owned-plants";
const dateText = (date: Date) => date.toLocaleDateString("cs-CZ", { day: "numeric", month: "long" });
const dueText = (date?: string) => date ? dateText(new Date(date)) : "dnes";
const addDays = (date: string | undefined, days: number) => new Date((date ? new Date(date) : new Date()).getTime() + days * 86_400_000);
const addMonths = (date: string | undefined, months: number) => { const result = new Date(date ?? Date.now()); result.setMonth(result.getMonth() + months); return result; };

export default function MyPlantsDashboard() {
  const [owned, setOwned] = useState<OwnedPlant[]>([]); const [slug, setSlug] = useState(plants[0].slug); const [nickname, setNickname] = useState(""); const [ready, setReady] = useState(false);
  useEffect(() => { const request = window.setTimeout(() => { const saved = localStorage.getItem(storageKey); if (saved) setOwned(JSON.parse(saved)); setReady(true); }, 0); return () => window.clearTimeout(request); }, []);
  const save = (items: OwnedPlant[]) => { setOwned(items); localStorage.setItem(storageKey, JSON.stringify(items)); };
  const addPlant = () => { const selected = plants.find((plant) => plant.slug === slug); if (!selected) return; save([...owned, { id: crypto.randomUUID(), plantSlug: selected.slug, nickname: nickname.trim() || selected.commonName }]); setNickname(""); };
  const items = useMemo(() => owned.map((entry) => ({ entry, plant: plants.find((plant) => plant.slug === entry.plantSlug)! })).filter((item) => item.plant), [owned]);
  const complete = (id: string, key: "fertilizedAt" | "repottedAt") => save(owned.map((item) => item.id === id ? { ...item, [key]: new Date().toISOString() } : item));
  return <div className="space-y-7"><WeatherAdvisor plantSlugs={items.map(({ entry }) => entry.plantSlug)} />
    <section className="rounded-3xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex items-center gap-3"><Plus className="text-emerald-700" /><div><h2 className="text-2xl font-semibold text-slate-900 dark:text-white">Přidat rostlinu</h2><p className="text-sm text-slate-500 dark:text-slate-300">Vyberte druh ze svého atlasu a pojmenujte ji.</p></div></div><div className="mt-4 grid gap-3"><label className="text-sm font-medium text-slate-700 dark:text-slate-200">Druh<select value={slug} onChange={(event) => setSlug(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white p-3 text-slate-900 dark:border-slate-700"><option value="">Vyberte rostlinu</option>{plants.map((plant) => <option key={plant.slug} value={plant.slug}>{plant.commonName} — {plant.latinName}</option>)}</select></label><label className="text-sm font-medium text-slate-700 dark:text-slate-200">Vlastní název<input value={nickname} onChange={(event) => setNickname(event.target.value)} placeholder="Např. Monstera v obýváku" className="mt-1 w-full rounded-xl border border-slate-200 bg-white p-3 text-slate-900 dark:border-slate-700" /></label><button onClick={addPlant} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white"><Plus size={18} />Přidat do mých rostlin</button></div></section>
    <section aria-labelledby="tasks" className="rounded-3xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex items-center gap-3"><Sprout className="text-emerald-700" /><div><h2 id="tasks" className="text-2xl font-semibold text-slate-900 dark:text-white">Moje úkoly</h2><p className="text-sm text-slate-500 dark:text-slate-300">Po potvrzení se termín automaticky přepočítá podle potřeb druhu.</p></div></div>{!ready ? <p className="mt-4 text-slate-500">Načítám vaše rostliny…</p> : items.length === 0 ? <p className="mt-4 rounded-2xl bg-emerald-50 p-4 text-emerald-900">Zatím tu nic není. Přidejte svou první rostlinu a připravíme jí plán péče.</p> : <div className="mt-5 space-y-4">{items.map(({ entry, plant }) => { const profile = getCareProfile(plant); const nextFertilize = addDays(entry.fertilizedAt, profile.fertilizeDays); const nextRepot = addMonths(entry.repottedAt, profile.repotMonths); return <article key={entry.id} className="rounded-2xl border border-slate-100 p-4 dark:border-slate-700"><h3 className="text-lg font-semibold text-slate-900 dark:text-white">{entry.nickname}</h3><p className="text-sm italic text-slate-500 dark:text-slate-300">{plant.latinName}</p><div className="mt-4 grid gap-2"><button onClick={() => complete(entry.id, "fertilizedAt")} className="flex items-center justify-between rounded-xl bg-amber-50 p-3 text-left text-amber-950"><span><b>Hnojení</b><br /><small>Další termín: {dueText(entry.fertilizedAt ? nextFertilize.toISOString() : undefined)}{entry.fertilizedAt ? ` (za ${profile.fertilizeDays} dní od dneška)` : ""}</small></span><span className="grid h-7 w-7 place-items-center rounded-full bg-white"><Check size={16} /></span></button><button onClick={() => complete(entry.id, "repottedAt")} className="flex items-center justify-between rounded-xl bg-sky-50 p-3 text-left text-sky-950"><span><b>Přesazení</b><br /><small>Další termín: {dueText(entry.repottedAt ? nextRepot.toISOString() : undefined)}{entry.repottedAt ? ` (za ${profile.repotMonths} měsíců od dneška)` : ""}</small></span><span className="grid h-7 w-7 place-items-center rounded-full bg-white"><RotateCcw size={16} /></span></button></div></article>; })}</div>}</section>
    <section className="rounded-3xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex items-center gap-3"><Leaf className="text-emerald-700" /><div><h2 className="text-2xl font-semibold text-slate-900 dark:text-white">Moje rostliny</h2><p className="text-sm text-slate-500 dark:text-slate-300">Rychlý přehled stanoviště a toho, co mají rády.</p></div></div><div className="mt-4 grid gap-3">{items.map(({ entry, plant }) => { const profile = getCareProfile(plant); return <article key={entry.id} className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800"><h3 className="font-semibold text-slate-900 dark:text-white">{entry.nickname}</h3><p className="mt-2 text-sm text-slate-700 dark:text-slate-200"><b>Stanoviště:</b> {profile.sunlight}</p><p className="mt-1 text-sm text-slate-700 dark:text-slate-200"><b>Má ráda:</b> {profile.likes}</p><p className="mt-1 text-sm text-slate-700 dark:text-slate-200"><b>Nemá ráda:</b> {profile.avoids}</p></article>; })}</div></section>
  </div>;
}
